# Generated by Django 2.2.9 on 2020-01-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_weathervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathervalue',
            name='name',
            field=models.CharField(default='unnamed', max_length=50),
        ),
    ]
